name: projected-gats-metric
channels:
  - conda-forge
dependencies:
  - cython==3.0.5
  - python==3.10.0
  - pip==23.3.1
  - gcc==13.2.0 
  - gxx==13.2.0
  - gfortran==13.2.0
  - tbb==2021.10.0
  - pip:
      - absl-py==1.2.0
      - click==8.1.3
      - fiftyone==0.22.3
      - Jinja2==3.1.2
      - lightgbm==4.1.0
      - numpy==1.26.1
      - open3d==0.17.0
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - optuna==3.4.0
      - packaging==23.2
      - pandas==2.1.2
      - piq==0.8.0
      - pymeshlab==2022.2.post4
      - ray==2.8.0
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.13.0
      - skops==0.6.0
      - torch==2.1.0
      - torchvision==0.16.0
      - tqdm==4.66.1
      - tune-sklearn==0.5.0
      - virtualenv==20.14.1
      - xgboost==2.0.1
      - xlsxwriter==3.1.9
      - SimpleITK==2.3.1
      - six==1.16.0
      - tensorflow-cpu==2.15.0